import time,datetime
print(time.asctime())
x=datetime.datetime.now()
print(x)
print(x.day)
print(x.month)
print(x.year)
print(x.hour)
print(x.minute)
print(x.second)
print(x.date())
print(x.strftime("%B"))
print(x.strftime("%A"))

time.sleep(3)
print('i selpt')